[package]
name = "devrandom"
version = "0.1.0"
authors = ["Matthew Piziak <matthew.piziak@gmail.com>"]

[dependencies]
rand = "0.3"
futures = "0.1.3"
tiny-keccak = "1.1"
arrayvec = "0.3.20"

[replace]
'futures:0.1.3' = { git = "https://github.com/alexcrichton/futures-rs" }
